services:
  - type: web
    name: health-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run home.py --server.port 10000 --server.address 0.0.0.0
